# Generated by Django 2.1.3 on 2018-12-18 00:27

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapistprofile',
            name='preferred_time',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('EARLY MORNING (6-8)', 'Early Morning (6-8)'), ('MORNING (8-11)', 'Morning (8-11)'), ('NOON (12-2)', 'Noon (12-2)'), ('LATE AFTERNOON (2-5)', 'Late Afternoon (2-5)'), ('EVENING (5-9)', 'Evening (5-9)'), ('NIGHT (9-11)', 'Night (9-11)')], max_length=100),
        ),
    ]
