# Generated by Django 2.1.3 on 2018-12-18 00:27

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20181218_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapistprofile',
            name='preferred_days',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=100),
        ),
    ]
